name: publiclibrary
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.1.5 <4.0.0'

dependencies: 
  get_cli: ^1.8.4
  google_fonts: ^4.0.4
  dio: 5.4.0
  pretty_dio_logger: ^1.3.1
  get_storage: ^2.1.1
  lottie: ^1.3.5
  form_validator: ^2.1.1
  font_awesome_flutter: ^10.7.0
  device_info_plus: ^9.1.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  auto_size_text: ^3.0.0

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/

